sudo: required

cache:
  directories:
  - $HOME/.m2

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

install:
  - npm install --prefix blog --silent
  - npm install --prefix comment --silent
  - npm install --prefix statistics --silent
  - npm install --prefix web-client --silent

script:
  - npm run test --prefix blog
  - npm run test --prefix comment
  - mvn package -f gateway --quiet
  - mvn package -f media --quiet
  - mvn package -f profile --quiet
  - mvn package -f registry --quiet
  - npm run test --prefix statistics
  - mvn package -f storage --quiet
  - mvn package -f uaa --quiet
  - npm run build:ssr --prefix web-client --silent

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  - export BLOG=egorrepnikov/artaeum-blog
  - docker build -t $BLOG:$COMMIT ./blog
  - docker tag $BLOG:$COMMIT $BLOG:$TAG
  - docker push $BLOG

  - export COMMENT=egorrepnikov/artaeum-comment
  - docker build -t $COMMENT:$COMMIT ./comment
  - docker tag $COMMENT:$COMMIT $COMMENT:$TAG
  - docker push $COMMENT

  - export GATEWAY=egorrepnikov/artaeum-gateway
  - docker build -t $GATEWAY:$COMMIT ./gateway
  - docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
  - docker push $GATEWAY

  - export MEDIA=egorrepnikov/artaeum-media
  - docker build -t $MEDIA:$COMMIT ./media
  - docker tag $MEDIA:$COMMIT $MEDIA:$TAG
  - docker push $MEDIA

  - export PROFILE=egorrepnikov/artaeum-profile
  - docker build -t $PROFILE:$COMMIT ./profile
  - docker tag $PROFILE:$COMMIT $PROFILE:$TAG
  - docker push $PROFILE

  - export REGISTRY=egorrepnikov/artaeum-registry
  - docker build -t $REGISTRY:$COMMIT ./registry
  - docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
  - docker push $REGISTRY

  - export STATISTICS=egorrepnikov/artaeum-statistics
  - docker build -t $STATISTICS:$COMMIT ./statistics
  - docker tag $STATISTICS:$COMMIT $STATISTICS:$TAG
  - docker push $STATISTICS

  - export STORAGE=egorrepnikov/artaeum-storage
  - docker build -t $STORAGE:$COMMIT ./storage
  - docker tag $STORAGE:$COMMIT $STORAGE:$TAG
  - docker push $STORAGE

  - export UAA=egorrepnikov/artaeum-uaa
  - docker build -t $UAA:$COMMIT ./uaa
  - docker tag $UAA:$COMMIT $UAA:$TAG
  - docker push $UAA

  - export WEB_CLIENT=egorrepnikov/artaeum-web-client
  - docker build -t $WEB_CLIENT:$COMMIT ./web-client
  - docker tag $WEB_CLIENT:$COMMIT $WEB_CLIENT:$TAG
  - docker push $WEB_CLIENT
