version: '2.1'

services:

  config:
    build: config

  registry:
    build: registry

  gateway:
    build: gateway

  uaa:
    build: uaa

  profile:
    build: profile

  media:
    build: media

  chat:
   build: chat

  chat-sidecar:
    build: chat-sidecar

  comment:
    build: comment

  comment-sidecar:
    build: comment-sidecar

  storage:
    build: storage
