version: '2.2'

services:

  docker-host:
    image: qoomon/docker-host
    cap_add: ['NET_ADMIN', 'NET_RAW']
    mem_limit: 4M
    restart: on-failure

  config:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-config
    restart: always

  registry:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-registry
    restart: always
    ports:
    - 8761:8761

  gateway:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      GATEWAY_SERVICE_PASSWORD: $GATEWAY_SERVICE_PASSWORD
      CHAT_SERVICE_URL: $CHAT_SERVICE_URL
      COMMENT_SERVICE_URL: $COMMENT_SERVICE_URL
      BLOG_SERVICE_URL: $BLOG_SERVICE_URL
    image: egorrepnikov/artaeum-gateway
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
    - 8081:4000

  web-client:
    image: egorrepnikov/artaeum-web-client
    restart: always
    ports:
    - 8080:80

  uaa:
    environment:
      EMAIL_ADDRESS: $EMAIL_ADDRESS
      EMAIL_PASSWORD: $EMAIL_PASSWORD
      MAIL_URL: $MAIL_URL
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      POSTGRES_URL: $UAA_POSTGRES_URL
      POSTGRES_USER: $UAA_POSTGRES_USER
      POSTGRES_PASSWORD: $UAA_POSTGRES_PASSWORD
      UAA_SERVICE_PASSWORD: $UAA_SERVICE_PASSWORD
      PROFILE_SERVICE_PASSWORD: $PROFILE_SERVICE_PASSWORD
      MEDIA_SERVICE_PASSWORD: $MEDIA_SERVICE_PASSWORD
      GATEWAY_SERVICE_PASSWORD: $GATEWAY_SERVICE_PASSWORD
      CHAT_SERVICE_PASSWORD: $CHAT_SERVICE_PASSWORD
      COMMENT_SERVICE_PASSWORD: $COMMENT_SERVICE_PASSWORD
      STORAGE_SERVICE_PASSWORD: $STORAGE_SERVICE_PASSWORD
      BLOG_SERVICE_PASSWORD: $BLOG_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-uaa
    restart: always
    depends_on:
      config:
        condition: service_healthy

  profile:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      POSTGRES_URL: $PROFILE_POSTGRES_URL
      POSTGRES_USER: $PROFILE_POSTGRES_USER
      POSTGRES_PASSWORD: $PROFILE_POSTGRES_PASSWORD
      PROFILE_SERVICE_PASSWORD: $PROFILE_SERVICE_PASSWORD
      STORAGE_SERVICE_PASSWORD: $STORAGE_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-profile
    restart: always
    depends_on:
      config:
        condition: service_healthy

  media:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MONGO_URI: $MEDIA_MONGO_URI
      MEDIA_SERVICE_PASSWORD: $MEDIA_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-media
    restart: always
    depends_on:
      config:
        condition: service_healthy

  comment:
    environment:
      MONGO_URI: $COMMENT_MONGO_URI
      COMMENT_SERVICE_PASSWORD: $CHAT_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-comment
    restart: always
    depends_on:
      config:
        condition: service_healthy

  storage:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      STORAGE_SERVICE_PASSWORD: $STORAGE_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-storage
    restart: always
    depends_on:
      config:
        condition: service_healthy
    volumes:
    - /home/ae/storage/profile:/profile
    - /home/ae/storage/blog:/blog

  blog:
    environment:
      MONGO_URI: $BLOG_MONGO_URI
      BLOG_SERVICE_PASSWORD: $BLOG_SERVICE_PASSWORD
      STORAGE_SERVICE_PASSWORD: $STORAGE_SERVICE_PASSWORD
      STORAGE_SERVICE_URI: $STORAGE_SERVICE_URI
    image: egorrepnikov/artaeum-blog
    restart: always
    depends_on:
      config:
        condition: service_healthy

  statistics:
    environment:
      MONGO_URI: $STATISTICS_MONGO_URI
      STATISTICS_SERVICE_PASSWORD: $STATISTICS_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-statistics
    restart: always
    depends_on:
      config:
        condition: service_healthy
