version: '2.1'

services:

  config:
    build: config

  registry:
    build: registry

  gateway:
    build: gateway
    ports:
      - 8080:4000

  uaa:
    build: uaa

  profile:
    build: profile

  media:
    build: media

  chat:
    build: chat
