version: '2.1'

services:

  config:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-config
    restart: always

  registry:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-registry
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
    - 8761:8761

  gateway:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      GATEWAY_SERVICE_PASSWORD: $GATEWAY_SERVICE_PASSWORD
      UAA_SERVICE_URL: $UAA_SERVICE_URL
      CHAT_SERVICE_URL: $CHAT_SERVICE_URL
      COMMENT_SERVICE_URL: $COMMENT_SERVICE_URL
      BLOG_SERVICE_URL: $BLOG_SERVICE_URL
    image: egorrepnikov/artaeum-gateway
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
    - 8080:4000

  uaa:
    environment:
      EMAIL_ADDRESS: $EMAIL_ADDRESS
      EMAIL_PASSWORD: $EMAIL_PASSWORD
      MAIL_URL: $MAIL_URL
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      UAA_SERVICE_PASSWORD: $UAA_SERVICE_PASSWORD
      PROFILE_SERVICE_PASSWORD: $PROFILE_SERVICE_PASSWORD
      MEDIA_SERVICE_PASSWORD: $MEDIA_SERVICE_PASSWORD
      GATEWAY_SERVICE_PASSWORD: $GATEWAY_SERVICE_PASSWORD
      CHAT_SERVICE_PASSWORD: $CHAT_SERVICE_PASSWORD
      COMMENT_SERVICE_PASSWORD: $COMMENT_SERVICE_PASSWORD
      STORAGE_SERVICE_PASSWORD: $STORAGE_SERVICE_PASSWORD
      BLOG_SERVICE_PASSWORD: $BLOG_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-uaa
    restart: always
    depends_on:
      config:
        condition: service_healthy

  uaa-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: uaa
    ports:
    - 5432:5432

  profile:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PROFILE_SERVICE_PASSWORD: $PROFILE_SERVICE_PASSWORD
      STORAGE_SERVICE_PASSWORD: $STORAGE_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-profile
    restart: always
    depends_on:
      config:
        condition: service_healthy

  profile-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: profile
      PGPORT: 5433
    ports:
    - 5433:5433

  media:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MONGO_USER: $MONGO_USER
      MONGO_PASSWORD: $MONGO_PASSWORD
      MEDIA_SERVICE_PASSWORD: $MEDIA_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-media
    restart: always
    depends_on:
      config:
        condition: service_healthy

  media-mongo:
    image: aashreys/mongo-auth:latest
    environment:
      AUTH: 'yes'
      MONGODB_ADMIN_USER: $MONGO_ADMIN_USER
      MONGODB_ADMIN_PASS: $MONGO_ADMIN_PASSWORD
      MONGODB_APPLICATION_USER: $MONGO_USER
      MONGODB_APPLICATION_PASS: $MONGO_PASSWORD
      MONGODB_APPLICATION_DATABASE: media
    ports:
    - 27000:27017

  chat:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MONGO_USER: $MONGO_USER
      MONGO_PASSWORD: $MONGO_PASSWORD
      CHAT_SERVICE_PASSWORD: $CHAT_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-chat
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
    - 8000:8000

  chat-mongo:
    image: aashreys/mongo-auth:latest
    environment:
      AUTH: 'yes'
      MONGODB_ADMIN_USER: $MONGO_ADMIN_USER
      MONGODB_ADMIN_PASS: $MONGO_ADMIN_PASSWORD
      MONGODB_APPLICATION_USER: $MONGO_USER
      MONGODB_APPLICATION_PASS: $MONGO_PASSWORD
      MONGODB_APPLICATION_DATABASE: chat
    ports:
    - 28000:27017

  chat-sidecar:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-chat-sidecar
    restart: always
    depends_on:
      config:
        condition: service_healthy

  comment:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MONGO_USER: $MONGO_USER
      MONGO_PASSWORD: $MONGO_PASSWORD
      COMMENT_SERVICE_PASSWORD: $CHAT_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-comment
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
    - 9000:9000

  comment-mongo:
    image: aashreys/mongo-auth:latest
    environment:
      AUTH: 'yes'
      MONGODB_ADMIN_USER: $MONGO_ADMIN_USER
      MONGODB_ADMIN_PASS: $MONGO_ADMIN_PASSWORD
      MONGODB_APPLICATION_USER: $MONGO_USER
      MONGODB_APPLICATION_PASS: $MONGO_PASSWORD
      MONGODB_APPLICATION_DATABASE: comment
    ports:
    - 29000:27017

  comment-sidecar:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-comment-sidecar
    restart: always
    depends_on:
      config:
        condition: service_healthy

  storage:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      STORAGE_SERVICE_PASSWORD: $STORAGE_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-storage
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
    - 10000:10000

  web-client:
    image: egorrepnikov/artaeum-web-client
    restart: always
    ports:
    - 80:80

  blog:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MONGO_USER: $MONGO_USER
      MONGO_PASSWORD: $MONGO_PASSWORD
      BLOG_SERVICE_PASSWORD: $BLOG_SERVICE_PASSWORD
      STORAGE_SERVICE_PASSWORD: $STORAGE_SERVICE_PASSWORD
      STORAGE_SERVICE_URI: $STORAGE_SERVICE_URI
    image: egorrepnikov/artaeum-blog
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
    - 11000:11000

  blog-mongo:
    image: aashreys/mongo-auth:latest
    environment:
      AUTH: 'yes'
      MONGODB_ADMIN_USER: $MONGO_ADMIN_USER
      MONGODB_ADMIN_PASS: $MONGO_ADMIN_PASSWORD
      MONGODB_APPLICATION_USER: $MONGO_USER
      MONGODB_APPLICATION_PASS: $MONGO_PASSWORD
      MONGODB_APPLICATION_DATABASE: blog
    ports:
    - 30000:27017

  blog-sidecar:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-blog-sidecar
    restart: always
    depends_on:
      config:
        condition: service_healthy
