version: '2.1'

services:

  config:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: config
    restart: always

  registry:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: registry
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
    - 8761:8761

  gateway:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      GATEWAY_SERVICE_PASSWORD: $GATEWAY_SERVICE_PASSWORD
    image: gateway
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
    - 80:4000

  uaa:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      UAA_SERVICE_PASSWORD: $UAA_SERVICE_PASSWORD
      PROFILE_SERVICE_PASSWORD: $PROFILE_SERVICE_PASSWORD
      MEDIA_SERVICE_PASSWORD: $MEDIA_SERVICE_PASSWORD
      GATEWAY_SERVICE_PASSWORD: $GATEWAY_SERVICE_PASSWORD
    image: uaa
    restart: always
    depends_on:
      config:
        condition: service_healthy

  uaa-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: uaa
    ports:
    - 5432:5432

  profile:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PROFILE_SERVICE_PASSWORD: $PROFILE_SERVICE_PASSWORD
    image: profile
    restart: always
    depends_on:
      config:
        condition: service_healthy

  profile-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: profile
      PGPORT: 5433
    ports:
    - 5433:5433

  media:
    environment:
      CONFIG_SERVICE_USER: $CONFIG_SERVICE_USER
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MONGO_USER: $MONGO_USER
      MONGO_PASSWORD: $MONGO_PASSWORD
      MEDIA_SERVICE_PASSWORD: $MEDIA_SERVICE_PASSWORD
    image: media
    restart: always
    depends_on:
      config:
        condition: service_healthy

  media-mongo:
    image: aashreys/mongo-auth:latest
    environment:
      AUTH: 'yes'
      MONGODB_ADMIN_USER: $MONGO_ADMIN_USER
      MONGODB_ADMIN_PASS: $MONGO_ADMIN_PASSWORD
      MONGODB_APPLICATION_USER: $MONGO_USER
      MONGODB_APPLICATION_PASS: $MONGO_PASSWORD
      MONGODB_APPLICATION_DATABASE: media
    ports:
    - 27017:27017
