server:
  servlet.context-path: /profile
  port: ${PORT:6000}

spring:
  application.name: profile
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    jpa:
      hibernate.ddl-auto: update
      properties.hibernate.temp.use_jdbc_metadata_defaults: false

security.oauth2.resource.user-info-uri: ${OAUTH2_USER_INFO_URI:http://uaa:5000/uaa/account/current}

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    nonSecurePort: ${HOSTPORT:${server.port}}
  client.serviceUrl.defaultZone: ${EUREKA_URL:http://registry:8761/eureka/}
