eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://registry:8761/eureka/}

security:
  oauth2:
    resource:
      user-info-uri: ${OAUTH2_USER_INFO_URI:http://uaa:5000/uaa/account/current}
