hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 101000

ribbon:
  ConnectTimeout: 25000
  ReadTimeout: 25000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 25000
    socket-timeout-millis: 25000
  routes:
    uaa:
      path: /uaa/**
      serviceId: uaa
      stripPrefix: false
    media:
      path: /media/**
      serviceId: media
      stripPrefix: false
    profile:
      path: /profile/**
      serviceId: profile
      stripPrefix: false
    storage:
      path: /storage/**
      serviceId: storage
      stripPrefix: false
    blog:
      path: /blog/**
      serviceId: blog
      stripPrefix: false
    chat:
      path: /chat/**
      serviceId: chat
      stripPrefix: false
    comment:
      path: /comment/**
      serviceId: comment
      stripPrefix: false
    statistics:
      path: /statistics/**
      serviceId: statistics
      stripPrefix: false

server:
  port: ${PORT:4000}

security:
  oauth2:
    client:
      clientId: gateway
      clientSecret: ${GATEWAY_SERVICE_PASSWORD}
      accessTokenUri: ${OAUTH2_ACCESS_TOKEN_URI:http://uaa:5000/uaa/oauth/token}
      grant-type: client_credentials
      scope: client.user
