server:
  servlet:
    context-path: /profile
  port: ${PORT:6000}

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://profile-postgres:5433/profile}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
