server:
  servlet:
    context-path: /profile
  port: ${PORT:6000}

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://profile-postgres:5433/profile}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

security:
  oauth2:
    client:
      clientId: profile
      clientSecret: ${PROFILE_SERVICE_PASSWORD}
      accessTokenUri: ${OAUTH2_ACCESS_TOKEN_URI:http://uaa:5000/uaa/oauth/token}
      grant-type: client_credentials
      scope: server
