server:
  servlet:
    context-path: /storage
  port: ${PORT:10000}
  max-http-header-size: 16777216

spring:
  http:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
  security:
    user:
      name: storage
      password: ${STORAGE_SERVICE_PASSWORD}

artaeum:
  resources: profile,blog
