server:
  servlet:
    context-path: /storage
  port: 10000

spring:
  http:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB

security:
  oauth2:
    client:
      clientId: storage
      clientSecret: ${STORAGE_SERVICE_PASSWORD}
      accessTokenUri: http://uaa:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
