server:
  servlet:
    context-path: /uaa
  port: 5000

spring:
  datasource:
    url: jdbc:postgresql://uaa-postgres:5432/uaa
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    protocol: smtp

artaeum:
  mail:
    url: ${MAIL_URL}
