server:
  servlet:
    context-path: /uaa
  port: ${PORT:5000}

spring:
  datasource:
    uri: ${POSTGRES_URI:jdbc:postgresql://postgres:password@uaa-postgres:5432/uaa}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  mail:
    host: smtp.yandex.ru
    port: 465
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    protocol: smtps
  thymeleaf:
    cache: true

security:
  oauth2:
    client:
      clientId: uaa
      clientSecret: ${UAA_SERVICE_PASSWORD}
      accessTokenUri: ${OAUTH2_ACCESS_TOKEN_URI:http://uaa:5000/uaa/oauth/token}
      grant-type: client_credentials
      scope: server

artaeum:
  mail:
    url: ${MAIL_URL}
  languages: en,ru
