server:
  servlet:
    context-path: /uaa
  port: 5000

spring:
  datasource:
    url: jdbc:postgresql://uaa-postgres:5432/uaa
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

security:
  oauth2:
    client:
      clientId: uaa
      clientSecret: ${UAA_SERVICE_PASSWORD}
      accessTokenUri: http://uaa:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
